Add @types/react as peer dep to lucide-react
Without this, in a PNPM + bazel setup, TypeScript cannot find react typings:

```
node_modules/.aspect_rules_js/lucide-react@0.453.0_814417300/node_modules/lucide-react/dist/lucide-react.d.ts(1,24): error TS7016: Could not find a declaration file for module 'react'. '/path/to/sandbox/darwin-sandbox/39/execroot/_main/bazel-out/darwin_x86_64-fastbuild/bin/node_modules/.aspect_rules_js/react@18.3.1/node_modules/react/index.js' implicitly has an 'any' type.
  If the 'react' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react'
```

Since the exported types depend on `@types/react`, I think this package should either declare `@types/react` as a direct or a peer dep. I chose a peer dep in this PR to mirror what's being done with `react`, but happy to change it!